apiVersion: v1
kind: Service
metadata:
  name: {{ include "clamav.fullname" . }}-clamd
  labels:
    {{- include "clamav.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: antivirus
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.clamd.config.tcpSocket }}
      protocol: TCP
      name: clamad
  selector:
    {{- include "clamav.selectorLabels" . | nindent 3 }}