{{- if .Values.persistentVolume.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clamav.pvcname" . }}
spec:
  accessModes: {{ .Values.persistentVolume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
  {{- if .Values.persistentVolume.storageClass }}
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  {{- end }}
{{- end }}
