---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mork.fullname" . }}-api
  labels: {{- include "mork.labels" . | nindent 4 }}
spec:
  ports:
    - name: "{{ .Values.service.port }}-tcp"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      {{- if (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.nodePort.http }}
      {{- end }}
  type: {{ .Values.service.type }}
  selector: 
    app.kubernetes.io/component: api
    {{- include "mork.selectorLabels" . | nindent 4 }}
