apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  nginx.conf: |
    server {
      listen {{ .Values.indico.service.port }};
      listen [::]:{{ .Values.indico.service.port }};
      server_name {{ .Values.indico.ingress.host }}

      access_log /var/log/nginx/access.log combined;
      access_log /dev/stdout combined;
      error_log  /var/log/nginx/error.log info;
      error_log  stderr info;

      root       /var/empty;

      sendfile on;

      # Serve static files
      location ~ ^/(images|fonts)(.*)/(.+?)(__v[0-9a-f]+)?\.([^.]+)$ {
        alias /opt/indico/static/$1$2/$3.$5;
      }

      location ~ ^/(css|dist|images|fonts)/(.*)$ {
        alias /opt/indico/static/$1/$2;
      }

      location / {
        proxy_pass http://{{ .Values.indico.service.name }}:59999;
        proxy_set_header Host $server_name;
        proxy_set_header X-Forwarded-Proto {{ .Values.indico.protocol }};
        client_max_body_size 1G;
      }

    }
