# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: E-Learning
  licenses: Apache-2.0
  images: |
    - name: apache-exporter
      image: docker.io/bitnami/apache-exporter:1.0.8-debian-12-r9
    - name: moodle
      image: docker.io/bitnami/moodle:4.4.3-debian-12-r2
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r30
apiVersion: v2
appVersion: 4.4.3
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 19.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Moodle(TM) LMS is an open source online Learning Management System widely used at universities, schools, and corporations. It is modular and highly adaptable to any type of online learning.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/moodle/img/moodle-stack-220x234.png
keywords:
- moodle
- learning
- php
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: moodle
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/moodle
version: 23.0.7
