{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and (include "opensearch.master.enabled" .) .Values.master.autoscaling.hpa.enabled }}
apiVersion: {{ include "common.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "opensearch.master.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: master
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ template "common.capabilities.statefulset.apiVersion" . }}
    kind: StatefulSet
    name: {{ include "opensearch.master.fullname" . }}
  minReplicas: {{ .Values.master.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .Values.master.autoscaling.hpa.maxReplicas }}
  metrics:
    {{- if .Values.master.autoscaling.hpa.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.master.autoscaling.hpa.targetCPU }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.master.autoscaling.hpa.targetCPU }}
        {{- end }}
    {{- end }}
    {{- if .Values.master.autoscaling.hpa.targetMemory }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.master.autoscaling.hpa.targetMemory }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.master.autoscaling.hpa.targetMemory }}
        {{- end }}
    {{- end }}
{{- end }}
