apiVersion: v1
kind: Secret
metadata:
  labels:
    app: richie
    service: richie
  name: "{{ .Values.richie.app.secret_name }}"
  namespace: "{{ .Values.namespace }}"
data:
  DJANGO_SECRET_KEY: {{ .Values.DJANGO_SECRET_KEY | b64enc }}
  DB_USER: {{ .Values.DB_USER | b64enc }}
  DB_PASSWORD: {{ .Values.DB_PASSWORD | b64enc }}
