apiVersion: v1
kind: Secret
metadata:
  labels:
    app: richie
    service: richie
  name: "{{ .Values.richie.app.secret_name }}"
  namespace: "{{ .Values.namespace }}"
data:
  DJANGO_SECRET_KEY: 'supersecret'
  # DJANGO_SENTRY_DSN: ' '
  DB_USER: 'edxapp_user'
  DB_PASSWORD: 'password'
