apiVersion: v1
kind: Service
metadata:
  labels:
    app: richie
    service: richie
    version: "{{ .Values.richie.app.image_tag }}"
    deployment_stamp: "{{ .Release.Name }}"
  name: richie-app-{{ .Release.Name }}  # name of the service should be host name in nginx
  namespace: "{{ .Values.namespace }}"
spec:
  ports:
  - name: 8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: richie
    deployment: "richie-app-{{ .Release.Name }}"
  type: ClusterIP
