{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.controlPlane.autoscaling.hpa.enabled (not .Values.controlPlane.useDaemonSet) }}
apiVersion: {{ include "common.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "apisix.control-plane.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    name: {{ template "apisix.control-plane.fullname" . }}
  minReplicas: {{ .Values.controlPlane.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .Values.controlPlane.autoscaling.hpa.maxReplicas }}
  metrics:
    {{- if .Values.controlPlane.autoscaling.hpa.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.controlPlane.autoscaling.hpa.targetCPU }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.controlPlane.autoscaling.hpa.targetCPU }}
        {{- end }}
    {{- end }}
    {{- if .Values.controlPlane.autoscaling.hpa.targetMemory }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.controlPlane.autoscaling.hpa.targetMemory }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.controlPlane.autoscaling.hpa.targetMemory }}
        {{- end }}
    {{- end }}
{{- end }}
