apiVersion: v1
kind: Service
metadata:
  name: "moodle"
spec:
  ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: moodle
    service: apache2
  type: ClusterIP