apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.data.pvc }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ $.Values.data.size }}
  {{- if $.Values.data.storageClass }}
  storageClassName: {{ $.Values.data.storageClass }}
  {{- end }}