# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: ApplicationServer
  licenses: Apache-2.0
  images: |
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r30
    - name: wildfly
      image: docker.io/bitnami/wildfly:33.0.2-debian-12-r0
apiVersion: v2
appVersion: 33.0.2
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Wildfly is a lightweight, open source application server, formerly known as JBoss, that implements the latest enterprise Java standards.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/wildfly/img/wildfly-stack-220x234.png
keywords:
- wildfly
- java
- http
- web
- application server
- jsp
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: wildfly
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/wildfly
version: 21.0.5
