# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: WorkFlow
  licenses: Apache-2.0
  images: |
    - name: airflow
      image: docker.io/bitnami/airflow:2.10.2-debian-12-r0
    - name: airflow-exporter
      image: docker.io/bitnami/airflow-exporter:0.20220314.0-debian-12-r47
    - name: airflow-scheduler
      image: docker.io/bitnami/airflow-scheduler:2.10.2-debian-12-r0
    - name: airflow-worker
      image: docker.io/bitnami/airflow-worker:2.10.2-debian-12-r0
    - name: git
      image: docker.io/bitnami/git:2.46.1-debian-12-r1
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r30
apiVersion: v2
appVersion: 2.10.2
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 20.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Airflow is a tool to express and execute workflows as directed acyclic graphs (DAGs). It includes utilities to schedule tasks, monitor task progress and handle task dependencies.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/airflow/img/airflow-stack-220x234.png
keywords:
- apache
- airflow
- workflow
- dag
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: airflow
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/airflow
version: 20.0.0
