
apiVersion: v1
kind: Secret
metadata:
  name: ckancredentials
type: Opaque

stringData:
  sysadminPassword: {{ .Values.ckan.sysadminPassword }}
  psqlMasterPassword: {{ .Values.ckan.psql.masterPassword }}
  smtpPassword: {{ .Values.ckan.smtp.password }} 
{{if .Values.ckan.psql.runOnAzure }}
  ckanSqlAlchemyUrl: "postgresql://{{ .Values.ckan.db.ckanDbUser }}@{{ .Values.ckan.db.ckanDbUrl }}:{{ .Values.ckan.db.ckanDbPassword }}@{{ .Values.ckan.db.ckanDbUrl }}/{{ .Values.ckan.db.ckanDbName }}"
  ckanDatastoreWriteUrl: "postgresql://{{ .Values.ckan.datastore.RwDbUser }}@{{ .Values.ckan.datastore.RwDbUrl }}:{{ .Values.ckan.datastore.RwDbPassword }}@{{ .Values.ckan.datastore.RwDbUrl }}/{{ .Values.ckan.datastore.RwDbName }}"
  ckanDatastoreReadUrl: "postgresql://{{ .Values.ckan.datastore.RoDbUser }}@{{ .Values.ckan.datastore.RoDbUrl }}:{{ .Values.ckan.datastore.RoDbPassword }}@{{ .Values.ckan.datastore.RoDbUrl }}/{{ .Values.ckan.datastore.RoDbName }}"
{{else }}
  ckanSqlAlchemyUrl: "postgresql://{{ .Values.ckan.db.ckanDbUser }}:{{ .Values.ckan.db.ckanDbPassword }}@{{ .Values.ckan.db.ckanDbUrl }}/{{ .Values.ckan.db.ckanDbName }}"
  ckanDatastoreWriteUrl: "postgresql://{{ .Values.ckan.datastore.RwDbUser }}:{{ .Values.ckan.datastore.RwDbPassword }}@{{ .Values.ckan.datastore.RwDbUrl }}/{{ .Values.ckan.datastore.RwDbName }}"
  ckanDatastoreReadUrl: "postgresql://{{ .Values.ckan.datastore.RoDbUser }}:{{ .Values.ckan.datastore.RoDbPassword }}@{{ .Values.ckan.datastore.RoDbUrl }}/{{ .Values.ckan.datastore.RoDbName }}" 
{{end }}
