{{- if .Values.solr.initialize.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: solr-init-configmap
data:
  solr-init.py: |
{{ .Files.Get "solr-init/solr-init.py" | indent 4 }}

{{- end }}