---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenny.fullname" . }}-service
  labels: {{- include "jenny.labels" . | nindent 4 }}
spec:
  ports:
    - name: "{{ .Values.nginx.port }}-tcp"
      port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
      protocol: TCP
      {{- if (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.nodePort.http }}
      {{- end }}
  type: {{ .Values.service.type }}
  selector: {{- include "jenny.selectorLabels" . | nindent 4 }}
