apiVersion: v2
appVersion: 1.3.0
description: ClamAV is the an opensource scanning software.
name: clamav
sources:
- https://hub.docker.com/r/clamav/clamav
- https://github.com/Cisco-Talos/clamav-docker
- https://github.com/Cisco-Talos/clamav
version: 0.0.1
