apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailcatcher.fullname" . }}
  labels:
    {{- include "mailcatcher.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 1080
      targetPort: 1080
      protocol: TCP
      name: http
    - port: 1025
      targetPort: 1025
      protocol: TCP
      name: smtp
  selector:
    {{- include "mailcatcher.selectorLabels" . | nindent 3 }}
