apiVersion: v2
appVersion: 5.0.1
description: Ralph, the ultimate Learning Record Store (and more!) for your learning
  analytics
icon: https://raw.githubusercontent.com/openfun/logos/main/ralph/ralph-color-dark.png
name: ralph
type: application
version: 0.5.1
