apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle-adhoc-task
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.adhoc_task.replicaCount }}
  selector:
    matchLabels:
      app: moodle
      service: adhoc-task
  template:
    metadata:
      annotations:
        checksum/db_config: {{ include (print $.Template.BasePath "/configmap-database.yaml") . | sha256sum }}
        checksum/http_config: {{ include (print $.Template.BasePath "/configmap-moodle.yaml") . | sha256sum }}
      labels:
        app: moodle
        service: adhoc-task
    spec:
      volumes:
      {{- include "moodle.volume_db_secret" $ | nindent 10 }}
      {{- include "moodle.volume_data" $ | nindent 10 }}
      containers:
        - name: moodle-adhoc-task
          {{- include "moodle.image" $ | nindent 10 }}
          args: 
            - adhoc-task
            - {{ $.Values.adhoc_task.ttl | quote }}
          env:
            {{- include "moodle.db_env" . | nindent 12 }}
            {{- include "moodle.redis_env" . | nindent 12 }}
            {{- include "moodle.http_env" . | nindent 12 }}
          volumeMounts:
            {{- include "moodle.mount_db_secret" $ | nindent 12 }}
            - mountPath: /var/moodledata/
              name: moodle-v-data