apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moodle
  {{- if $.Values.ingress.annotations }}
  annotations:
    {{- toYaml $.Values.ingress.annotations | nindent 4 }}
  {{- end }}

spec:
  {{- if $.Values.http.https.certificateSecretName }}
  tls:
  - hosts:
      - {{ $.Values.http.host }}
    secretName: {{ $.Values.http.https.certificateSecretName }}
  {{- end }}
  rules:
  - host: {{ $.Values.http.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: moodle
            port:
              number: 80