{{- if $.Values.moodle.admin.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.moodle.admin.passwordSecretName }}
data: 
  admin_password: {{ $.Values.moodle.admin.password | b64enc }}
{{- end }}