apiVersion: v2
appVersion: "3.1"
name: indico
description: "Indico from CERN"
version: 1.0.0
dependencies:
- name: postgresql
  version: "11.x"
  repository: https://charts.bitnami.com/bitnami
- name: redis
  version: "16.x"
  repository: https://charts.bitnami.com/bitnami
