{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.agent.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: {{ template "jaeger.agent.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: agent
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.agent.podLabels .Values.commonLabels ) "context" . ) }}
  podSelector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: agent
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.agent.networkPolicy.allowExternalEgress }}
  egress:
    - {}
  {{- else }}
  egress:
    # Allow dns resolution
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    # Allow outbound connections to other agent pods
    - ports:
        - port: {{ .Values.agent.containerPorts.binary }}
        - port: {{ .Values.agent.containerPorts.zipkin }}
        - port: {{ .Values.agent.containerPorts.admin }}
        - port: {{ .Values.agent.containerPorts.compact }}
        - port: {{ .Values.agent.containerPorts.config }}
      to:
        - podSelector:
            matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 14 }}
              app.kubernetes.io/component: agent
    # Allow outbound connections to other collector pods
    - ports:
        - port: {{ .Values.collector.containerPorts.binary }}
        - port: {{ .Values.collector.containerPorts.zipkin }}
        - port: {{ .Values.collector.containerPorts.grpc }}
        - port: {{ .Values.collector.containerPorts.admin }}
        - port: {{ .Values.collector.containerPorts.otlp.grpc }}
        - port: {{ .Values.collector.containerPorts.otlp.http }}
      to:
        - podSelector:
            matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 14 }}
              app.kubernetes.io/component: collector
    # Allow outbound connections to other query pods
    - ports:
        - port: {{ .Values.query.containerPorts.admin }}
      to:
        - podSelector:
            matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 14 }}
              app.kubernetes.io/component: query
    # Allow outbound connections to Cassandra
    - ports:
        - port: {{ include "jaeger.cassandra.port" . | trimAll "\"" | int }}
      {{- if .Values.cassandra.enabled }}
      to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: cassandra
              app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}
    {{- if .Values.agent.networkPolicy.extraEgress }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.agent.networkPolicy.extraEgress "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  ingress:
    - ports:
        - port: {{ .Values.agent.containerPorts.binary }}
        - port: {{ .Values.agent.containerPorts.zipkin }}
        - port: {{ .Values.agent.containerPorts.admin }}
        - port: {{ .Values.agent.containerPorts.compact }}
        - port: {{ .Values.agent.containerPorts.config }}
      {{- if not .Values.agent.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 14 }}
        - podSelector:
            matchLabels:
              {{ template "jaeger.agent.fullname" . }}-client: "true"
        {{- if .Values.agent.networkPolicy.ingressNSMatchLabels }}
        - namespaceSelector:
            matchLabels:
              {{- range $key, $value := .Values.agent.networkPolicy.ingressNSMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- if .Values.agent.networkPolicy.ingressNSPodMatchLabels }}
          podSelector:
            matchLabels:
              {{- range $key, $value := .Values.agent.networkPolicy.ingressNSPodMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- if .Values.agent.networkPolicy.extraIngress }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.agent.networkPolicy.extraIngress "context" $ ) | nindent 4 }}
    {{- end }}
{{- end }}
