apiVersion: apps/v1
kind: Deployment
metadata:
   name: {{ include "mailcatcher.fullname" . }}
   labels:
     {{- include "mailcatcher.selectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mailcatcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mailcatcher.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "mailcatcher.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" .Chart.AppVersion)  }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 1025
            protocol: TCP
          - containerPort: 1080
            protocol: TCP

