{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scdf.prometheus-proxy.fullname" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: prometheus-proxy
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- if or .Values.metrics.service.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.metrics.service.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  {{- if and .Values.metrics.service.clusterIP (eq .Values.metrics.service.type "ClusterIP") }}
  clusterIP: {{ .Values.metrics.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.metrics.service.type "LoadBalancer") (eq .Values.metrics.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.metrics.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.metrics.service.type "LoadBalancer") .Values.metrics.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- include "common.tplvalues.render" (dict "value" .Values.metrics.service.loadBalancerSourceRanges "context" $) | nindent 4 }}
  {{- end }}
  {{- if (and (eq .Values.metrics.service.type "LoadBalancer") (not (empty .Values.metrics.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.metrics.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.metrics.service.sessionAffinity }}
  sessionAffinity: {{ .Values.metrics.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.metrics.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.metrics.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ coalesce .Values.metrics.service.ports.http .Values.metrics.service.httpPort }}
      protocol: TCP
      targetPort: http
      {{- if and .Values.metrics.service.nodePorts.http (or (eq .Values.metrics.service.type "NodePort") (eq .Values.metrics.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.metrics.service.nodePorts.http }}
      {{- else }}
      nodePort: null
      {{- end }}
    - name: rsocket
      port: {{ coalesce .Values.metrics.service.ports.rsocket .Values.metrics.service.rsocketPort }}
      protocol: TCP
      targetPort: rsocket
      {{- if and .Values.metrics.service.nodePorts.rsocket (or (eq .Values.metrics.service.type "NodePort") (eq .Values.metrics.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.metrics.service.nodePorts.rsocket }}
      {{- else }}
      nodePort: null
      {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.metrics.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: prometheus-proxy
{{- end }}
